<?php
/**
 * Custom Filters 05
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'Hero Banner 2', 'cardealer' ),
	'template_category' => esc_html__( 'Hero Banner', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
	[vc_row full_width="stretch_row" content_placement="bottom" css=".vc_custom_1701341422006{padding-top: 80px !important;background-image: url(https://cardealer.potenzaglobalsolutions.com/wp-content/uploads/2023/11/banner-bg-map.png?id=11793) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}" el_class="home2-banner-bg overflow-visible"][vc_column cd_enable_responsive_settings="true" css=".vc_custom_1701341196175{padding-bottom: 100px !important;}" offset="vc_col-lg-6 vc_col-md-8" element_css_sm=".vc_custom_1701341196176{padding-bottom: 0px !important;}"][cd_section_title heading_tag="h2" title_align="text-left" style="style_3" section_title="Find What Are You Looking For" title_font_size_lg="70" title_font_size_md="60" title_font_size_sm="50" title_font_size_xs="42" title_line_height_lg="76" title_line_height_md="66" title_line_height_sm="56" title_line_height_xs="46"]

We provides best solution EV vehicles

[/cd_section_title][vc_custom_heading text="Over 4000 Latest Cars in Cardealer" font_container="tag:h3|font_size:30px|text_align:left|color:%23dd2f30|line_height:40px" use_theme_fonts="yes" css=".vc_custom_1701072526644{margin-top: 20px !important;margin-bottom: 20px !important;}"][vc_column_text css=".vc_custom_1701341190606{margin-bottom: 30px !important;padding-right: 80px !important;}"]Car Dealer is the most enticing, creative, modern and multipurpose auto dealer Premium WordPress Theme.[/vc_column_text][cd_button size="extra-large" title="More Information" style="black"][/vc_column][vc_column cd_enable_responsive_settings="true" offset="vc_col-lg-6 vc_col-md-4" css=".vc_custom_1701343087559{margin-bottom: -150px !important;}" element_css_md=".vc_custom_1701343087560{margin-bottom: -100px !important;}" element_css_sm=".vc_custom_1701343087560{margin-bottom: -50px !important;}"][vc_single_image source="external_link" custom_src="https://sampledata.potenzaglobalsolutions.com/cardealer-modern-vc/wp-content/uploads/2023/12/car-image-new.png" img_size="full" css=".vc_custom_1702968566789{margin-left: -270px !important;}" el_class="home-2-car-image"][vc_raw_html]JTNDc3R5bGUlM0UlMEEudmNfcm93LmhvbWUyLWJhbm5lci1iZyUyMCU3QiUwQSUyMCUyMCUyMCUyMGJhY2tncm91bmQtcG9zaXRpb24lM0ElMjA3NSUyNSUyMDQwcHglMjAlMjFpbXBvcnRhbnQlM0IlMjBiYWNrZ3JvdW5kLXNpemUlM0ElMjA4MDBweCUzQiUwQSU3RCUwQSU0MG1lZGlhJTIwJTI4bWF4LXdpZHRoJTNBJTIwOTkxcHglMjklMjAlN0IlMEElMjAlMjAlMjAlMjAudmNfcm93LmhvbWUyLWJhbm5lci1iZyUyMCU3QiUwQSUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGJhY2tncm91bmQtcG9zaXRpb24lM0ElMjAxMDAlMjUlMjAyNTBweCUyMCUyMWltcG9ydGFudCUzQiUyMGJhY2tncm91bmQtc2l6ZSUzQSUyMDUwMHB4JTNCJTBBJTIwJTIwJTIwJTIwJTdEJTBBJTdEJTBBJTQwbWVkaWElMjAlMjhtYXgtd2lkdGglM0ElMjA3NjdweCUyOSUyMCU3QiUwQSUyMCUyMCUyMCUyMC52Y19yb3cuaG9tZTItYmFubmVyLWJnJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwYmFja2dyb3VuZC1zaXplJTNBJTIwMHB4JTNCJTBBJTIwJTIwJTIwJTIwJTdEJTBBJTdEJTBBJTNDJTJGc3R5bGUlM0U=[/vc_raw_html][/vc_column][/vc_row][vc_row full_width="stretch_row" cd_enable_responsive_settings="true" css=".vc_custom_1701343134311{padding-top: 160px !important;padding-bottom: 80px !important;background: #db2d2e url(https://cardealer.potenzaglobalsolutions.com/wp-content/uploads/2023/11/section-bg-pattern-2.png?id=11795) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" element_css_md=".vc_custom_1701343134311{padding-top: 130px !important;padding-bottom: 80px !important;}" element_css_sm=".vc_custom_1701343134312{padding-top: 90px !important;padding-bottom: 80px !important;}"][vc_column][cd_vehicles_search condition_tab_lables="" vehicle_filters="" filter_background="light" hide_location_input="" filter_style="box" search_style="style-2" section_title="I Want to Buy"][/vc_column][/vc_row]
CONTENT',
);
