<?php
/**
 * Sample data items.
 *
 * @package cardealer/sample-data
 * @since   6.0.0
 */

/**
 * Sample data items.
 *
 * @return Array
 */
function cardealer_samples() {
	// phpcs:disable WordPress.Arrays.MultipleStatementAlignment
	$samples = array(
		// Classic - WPBakery.
		'classic-vc' => array(
			'id'          => 'classic-vc',
			'name'        => esc_html__( 'Classic (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/',
			'home_page'   => esc_html__( 'Home', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
				'top_menu'     => esc_html__( 'Top Bar Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-1.zip',
			),
			'builder_type' => 'wpbakery',
			'sample_type'  => 'base',
		),
		'classic-vc-home-02' => array(
			'id'          => 'classic-vc-home-02',
			'name'        => esc_html__( 'Home 2', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-2/',
			'home_page'   => esc_html__( 'Home 2', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 2 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-2/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-2.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-2.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-03'        => array(
			'id'          => 'classic-vc-home-03',
			'name'        => esc_html__( 'Home 3', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-3/',
			'home_page'   => esc_html__( 'Home 3', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 3 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-3/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-3.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-3.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-04'        => array(
			'id'          => 'classic-vc-home-04',
			'name'        => esc_html__( 'Home 4', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-4/',
			'home_page'   => esc_html__( 'Home 4', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 4 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-4/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-4.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-4.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-05'        => array(
			'id'          => 'classic-vc-home-05',
			'name'        => esc_html__( 'Home 5', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-5/',
			'home_page'   => esc_html__( 'Home 5', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 5 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-5/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-5.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-5.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-06'        => array(
			'id'          => 'classic-vc-home-06',
			'name'        => esc_html__( 'Home 6', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-6/',
			'home_page'   => esc_html__( 'Home 6', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 6 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-6/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-6.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-6.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-07'        => array(
			'id'          => 'classic-vc-home-07',
			'name'        => esc_html__( 'Home 7', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-7/',
			'home_page'   => esc_html__( 'Home 7', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 7 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-7/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-7.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-7.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-08'        => array(
			'id'          => 'classic-vc-home-08',
			'name'        => esc_html__( 'Home 8', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-8/',
			'home_page'   => esc_html__( 'Home 8', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 8 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-8/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-8.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-8.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-09'        => array(
			'id'          => 'classic-vc-home-09',
			'name'        => esc_html__( 'Home 9', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-9/',
			'home_page'   => esc_html__( 'Home 9', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 9 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-9/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-9.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-9.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-10'        => array(
			'id'          => 'classic-vc-home-10',
			'name'        => esc_html__( 'Home 10', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-10/',
			'home_page'   => esc_html__( 'Home 10', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 10 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-10/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-10.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'cardealer-slider-10.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-11'        => array(
			'id'          => 'classic-vc-home-11',
			'name'        => esc_html__( 'Home Directory', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-11/',
			'home_page'   => esc_html__( 'Home Directory', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 11 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-11/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-11.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-12'        => array(
			'id'          => 'classic-vc-home-12',
			'name'        => esc_html__( 'Car Landing', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-12/',
			'home_page'   => esc_html__( 'Car Landing', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 12 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/home-12/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-12.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-home-inventory' => array(
			'id'          => 'classic-vc-home-inventory',
			'name'        => esc_html__( 'Home - Inventory', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/cars/?layout-style=lazyload',
			'home_page'   => esc_html__( 'Home - Inventory', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home - Inventory content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/cars/?layout-style=lazyload',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-inventory.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),
		'classic-vc-services-new'   => array(
			'id'          => 'classic-vc-services-new',
			'name'        => esc_html__( 'Car Service', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/car-service',
			'home_page'   => esc_html__( 'Car Service', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import car service content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-vc/car-service',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-services-new.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'theme_options'     => array(
				'header_type' => 'boxed',
			),
			'revsliders'  => array(
				'car-service.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-vc',
		),

		// Classic - Elementor.
		'classic-el' => array(
			'id'          => 'classic-el',
			'name'        => esc_html__( 'Classic (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/',
			'home_page'   => esc_html__( 'Home', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Primary Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-default.zip',
			),
			'builder_type' => 'elementor',
			'sample_type'  => 'base',
		),
		'classic-el-home-02'  => array(
			'id'          => 'classic-el-home-02',
			'name'        => esc_html__( 'Home 2', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-2/',
			'home_page'   => esc_html__( 'Home 2', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 2 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-2/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-2.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-2.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-03'  => array(
			'id'          => 'classic-el-home-03',
			'name'        => esc_html__( 'Home 3', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-3/',
			'home_page'   => esc_html__( 'Home 3', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 3 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-3/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-3.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-3.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-04'  => array(
			'id'          => 'classic-el-home-04',
			'name'        => esc_html__( 'Home 4', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-4/',
			'home_page'   => esc_html__( 'Home 4', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 4 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-4/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-4.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-4.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-05'  => array(
			'id'          => 'classic-el-home-05',
			'name'        => esc_html__( 'Home 5', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-5/',
			'home_page'   => esc_html__( 'Home 5', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 5 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-5/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-5.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-5.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),

		'classic-el-home-06'  => array(
			'id'          => 'classic-el-home-06',
			'name'        => esc_html__( 'Home 6', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-6/',
			'home_page'   => esc_html__( 'Home 6', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 6 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-6/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-6.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-6.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),

		'classic-el-home-07'  => array(
			'id'          => 'classic-el-home-07',
			'name'        => esc_html__( 'Home 7', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-7/',
			'home_page'   => esc_html__( 'Home 7', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 7 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-7/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-7.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-7.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),

		'classic-el-home-08'  => array(
			'id'          => 'classic-el-home-08',
			'name'        => esc_html__( 'Home 8', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-8/',
			'home_page'   => esc_html__( 'Home 8', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 8 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-8/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-8.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-8.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),

		'classic-el-home-09'  => array(
			'id'          => 'classic-el-home-09',
			'name'        => esc_html__( 'Home 9', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-9/',
			'home_page'   => esc_html__( 'Home 9', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 9 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-9/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-9.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-9.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-10'  => array(
			'id'          => 'classic-el-home-10',
			'name'        => esc_html__( 'Home 10', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-10/',
			'home_page'   => esc_html__( 'Home 10', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 10 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-10/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-10.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				'home-10.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-11'  => array(
			'id'          => 'classic-el-home-11',
			'name'        => esc_html__( 'Home Directory', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-11/',
			'home_page'   => esc_html__( 'Home 11', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 11 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-11/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-11.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-home-12'  => array(
			'id'          => 'classic-el-home-12',
			'name'        => esc_html__( 'Car Landing', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-12/',
			'home_page'   => esc_html__( 'Home 12', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Home Page 12 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/home-12/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-home-12.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),
		'classic-el-services' => array(
			'id'          => 'classic-el-services',
			'name'        => esc_html__( 'Car Service', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/classic-el/car-service/',
			'home_page'   => esc_html__( 'Car Service', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import car service content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/classic-el/car-service/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/classic-services-new.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'theme_options'     => array(
				'header_type' => 'boxed',
			),
			'revsliders'  => array(
				'car-service.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'classic-el',
		),

		// Modern - WPBakery.
		'modern-vc' => array(
			'id'          => 'modern-vc',
			'name'        => esc_html__( 'Modern (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/',
			'home_page'   => esc_html__( 'Home Modern', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/elementor',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type' => 'wpbakery',
			'sample_type'  => 'base',
		),
		'modern-vc-home-02' => array(
			'id'          => 'modern-vc-home-02',
			'name'        => esc_html__( 'Modern Home 2', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/home-2/',
			'home_page'   => esc_html__( 'Modern Home 2', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Modern Home 2 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/home-2/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-2.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'modern-vc',
		),
		'modern-vc-home-03' => array(
			'id'          => 'modern-vc-home-03',
			'name'        => esc_html__( 'Modern Home 3', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/home-3/',
			'home_page'   => esc_html__( 'Modern Home 3', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Modern Home 3 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/home-3/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-3.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type'  => 'wpbakery',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'modern-vc',
		),

		// Modern - Elementor.
		'modern-el' => array(
			'id'          => 'modern-el',
			'name'        => esc_html__( 'Modern (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/elementor/',
			'home_page'   => esc_html__( 'Home Modern', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/elementor',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Primary Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type' => 'elementor',
			'sample_type'  => 'base',
		),
		'modern-el-home-02' => array(
			'id'          => 'modern-el-home-02',
			'name'        => esc_html__( 'Modern Home 2', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/elementor/home-2/',
			'home_page'   => esc_html__( 'Modern Home 2', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Modern Home 2 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/home-2/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-2.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Primary Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'modern-el',
		),
		'modern-el-home-03' => array(
			'id'          => 'modern-el-home-03',
			'name'        => esc_html__( 'Modern Home 3', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/elementor/home-3/',
			'home_page'   => esc_html__( 'Modern Home 3', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( "This sample will import Modern Home 3 content and set it as the front page. If the page already exists, then the page won't get imported. If you wanted to import the page, please rename the page then try again.", 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/home-3/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/modern-3.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Primary Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type'  => 'elementor',
			'sample_type'   => 'sub_sample',
			'sample_parent' => 'modern-el',
		),

		// Electro - WPBakery.
		'electro-vc' => array(
			'id'          => 'electro-vc',
			'name'        => esc_html__( 'Electro (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/electro-vc/',
			'home_page'   => esc_html__( 'Home EV', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/electro-vc/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/electro-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Main Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type' => 'wpbakery',
			'sample_type'  => 'base',
		),

		// Electro - Elementor.
		'electro-el' => array(
			'id'          => 'electro-el',
			'name'        => esc_html__( 'Electro (Base)', 'cardealer' ),
			'demo_url'    => 'https://cardealer.potenzaglobalsolutions.com/electro-el/',
			'home_page'   => esc_html__( 'Home EV', 'cardealer' ),
			'blog_page'   => esc_html__( 'Blog', 'cardealer' ),
			'message'     => esc_html__( 'Importing demo content will import Pages, Posts, Testimonials, Teams, FAQs, Menus, Widgets and Theme Options. Importing sample data will override current widgets and theme options. It can take some time to complete the import process.', 'cardealer' ),
			'preview_url' => 'https://cardealer.potenzaglobalsolutions.com/electro-el/',
			'previwe_img' => esc_url( get_template_directory_uri() . '/includes/sample_data/images/electro-base.png' ),
			'menus'       => array(
				'primary-menu' => esc_html__( 'Primary Menu', 'cardealer' ),
				'footer-menu'  => esc_html__( 'Footer Menu', 'cardealer' ),
			),
			'revsliders'  => array(
				// 'home-default.zip',
			),
			'builder_type' => 'elementor',
			'sample_type'  => 'base',
		),
	);
	// phpcs:enable WordPress.Arrays.MultipleStatementAlignment

	array_walk( $samples, 'cardealer_samples_set_data_paths' );

	return $samples;
}
