<?php
/**
 * About Bg Section
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'Infobox 6', 'cardealer' ),
	'template_category' => esc_html__( 'Infobox New', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
<p>[vc_row full_width="stretch_row" equal_height="yes" css=".vc_custom_1702358465679{background-color: #15181f !important;}" el_id="1698833663169-f89e9e92-364b"][vc_column cd_enable_responsive_settings="true" css=".vc_custom_1698833768106{padding-top: 120px !important;padding-right: 100px !important;padding-bottom: 120px !important;}" el_class="text-white" offset="vc_col-lg-6 vc_col-md-6" element_css_md=".vc_custom_1698833768107{padding-right: 50px !important;padding-bottom: 100px !important;}" element_css_sm=".vc_custom_1698833768107{padding-right: 15px !important;padding-bottom: 80px !important;}" el_id="1698833663193-675cfb8a-0c88"][cd_space desktop="120" tablet="100" portrait="80" mobile="80" mobile_portrait="80"][cd_section_title heading_tag="h2" title_align="text-left" show_content="true" style="style_3" section_title="Why Choose Our Car Services" title_color="#f9dd22" description_color="#81d742" content_color="#81d742" section_sub_title="Our Car Services" title_font_size_lg="" title_font_size_md="44" title_font_size_sm="38" title_font_size_xs="32" title_line_height_lg="" title_line_height_md="52" title_line_height_sm="46" title_line_height_xs="40"]Car Dealer is the most enticing, creative, modern and multipurpose auto dealer Premium WordPress Theme. Suitable for any car dealer websites, business or corporate websites.[/cd_section_title][vc_empty_space height="50px"][cd_infobox title_tag="h4" icon_type="flaticon" icon_shape="round" infobox_icon_type="flat" style="style-2" title="Brake Check &amp; Services" description="Galley simply dummy text lorem Ipsum is of the printin k a of type and" css=".vc_custom_1696939766993{margin-bottom: 30px !important;border-bottom-width: 1px !important;padding-bottom: 30px !important;border-bottom-color: rgba(255,255,255,0.1) !important;border-bottom-style: solid !important;border-radius: 1px !important;}" title_color="#ffffff" description_color="#eaeaea"][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-inspection" icon_shape="round" infobox_icon_type="flat" style="style-2" title="Online Appointment" description="Galley simply dummy text lorem Ipsum is of the printin k a of type and" title_color="#ffffff" description_color="#eaeaea"][/vc_column][vc_column cd_enable_responsive_settings="true" css=".vc_custom_1701847973211{margin-right: -350px !important;background-image: url(https://sampledata.potenzaglobalsolutions.com/cardealer-electro-vc/wp-content/uploads/2023/12/12-1.jpg?id=12034) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="video-button-custom" offset="vc_col-lg-6 vc_col-md-6" element_css_sm=".vc_custom_1701847973212{margin-right: -15px !important;margin-left: -15px !important;}" element_css_md=".vc_custom_1701847973211{margin-right: -110px !important;}" el_id="1698833663261-268eeea0-f597"][vc_empty_space height="100px"][vc_empty_space height="100px"][/vc_column][/vc_row]</p>
CONTENT',
);
