<?php
/**
 * About Bg Section
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'Infobox 4', 'cardealer' ),
	'template_category' => esc_html__( 'Infobox New', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
<p>[vc_row cd_enable_responsive_settings="true" css=".vc_custom_1700229790576{padding-top: 110px !important;padding-bottom: 110px !important;}" element_css_sm=".vc_custom_1700229790576{padding-top: 90px !important;padding-bottom: 90px !important;}" element_css_xs=".vc_custom_1700229790577{padding-top: 70px !important;padding-bottom: 70px !important;}"][vc_column][vc_row_inner][vc_column_inner offset="vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-1 vc_col-md-10"][cd_section_title heading_tag="h2" title_align="text-center" style="style_3" section_title="Our Work Process" title_font_size_lg="" title_font_size_md="40" title_font_size_sm="36" title_font_size_xs="32" title_line_height_lg="" title_line_height_md="50" title_line_height_sm="46" title_line_height_xs="42"][/cd_section_title][vc_column_text css=".vc_custom_1696845474055{margin-top: 20px !important;margin-bottom: 40px !important;}"]</p>
<p style="text-align: center;">Car Dealer is the most enticing, creative, modern and multipurpose auto dealer Premium WordPress Theme. Suitable for any car dealer websites, business or corporate websites.</p>
<p>[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="middle" css=".vc_custom_1697097645981{margin-top: 15px !important;}"][vc_column_inner width="1/2" cd_enable_responsive_settings="true" css=".vc_custom_1700227085978{margin-bottom: 50px !important;padding-right: 50px !important;}" offset="vc_col-lg-4 vc_col-md-4 vc_col-xs-12" element_css_sm=".vc_custom_1700227085979{margin-bottom: 0px !important;padding-right: 15px !important;padding-left: 15px !important;}"][cd_infobox title_tag="h4" icon_type="flaticon" style="style-1" title="Personal attention" description="The printin leap v lorem Ipsum is simply dummy k a galley of."][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-battery" style="style-1" title="Receive up front quote" description="The printin leap v lorem Ipsum is simply dummy k a galley of." css=".vc_custom_1700227028794{margin-top: 50px !important;margin-bottom: 50px !important;}"][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-car-wash" style="style-1" title="Online Appointment" description="The printin leap v lorem Ipsum is simply dummy k a galley of."][/vc_column_inner][vc_column_inner width="1/3" offset="vc_hidden-sm vc_hidden-xs"][vc_single_image source="external_link" custom_src="https://sampledata.potenzaglobalsolutions.com/cardealer-modern-vc/wp-content/uploads/2023/12/car-top.png" img_size="full" alignment="center"][/vc_column_inner][vc_column_inner width="1/2" cd_enable_responsive_settings="true" css=".vc_custom_1700227093450{margin-bottom: 50px !important;padding-left: 50px !important;}" offset="vc_col-lg-4 vc_col-md-4 vc_col-xs-12" element_css_sm=".vc_custom_1700227093452{margin-bottom: 0px !important;padding-left: 15px !important;}" element_css_xs=".vc_custom_1700227093452{margin-top: 50px !important;}"][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-gas-station" style="style-1" title="Share requirement" description="The printin leap v lorem Ipsum is simply dummy k a galley of."][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-car-wash" style="style-1" title="Pay post service" description="The printin leap v lorem Ipsum is simply dummy k a galley of." css=".vc_custom_1700227066347{margin-top: 50px !important;margin-bottom: 50px !important;}"][cd_infobox title_tag="h4" icon_type="flaticon" icon_flaticon="glyph-icon flaticon-alloy-wheel" style="style-1" title="Schedule appointment" description="The printin leap v lorem Ipsum is simply dummy k a galley of."][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>
CONTENT',
);
