<?php
/**
 *Video 04
 *
 * @package Cardealer
 */

return array(
	'name'              => esc_html__( 'Video with Counter', 'cardealer' ),
	'template_category' => esc_html__( 'Video', 'cardealer' ),
	'disabled'          => true, // Disable it to not show in the default tab.
	'content'           => '<<<CONTENT
<p>[vc_row full_width="stretch_row" cd_overlay_opacity="60" cd_enable_responsive_settings="true" cd_enable_overlay="true" css=".vc_custom_1702282377224{padding-top: 170px !important;padding-bottom: 250px !important;background-image: url(https://sampledata.potenzaglobalsolutions.com/cardealer-modern-vc/wp-content/uploads/2021/12/placeholder_1920x800.jpg?id=7591) !important;}" cd_overlay_color="#16181e" element_css_md=".vc_custom_1702282377225{padding-top: 130px !important;padding-bottom: 230px !important;}" element_css_sm=".vc_custom_1702282377225{padding-top: 100px !important;padding-bottom: 200px !important;}"][vc_column el_class="text-center" offset="vc_col-lg-2 vc_col-md-1"][/vc_column][vc_column offset="vc_col-lg-8 vc_col-md-10" el_class="text-center text-white"][cd_video_button video_link="https://www.youtube.com/watch?v=Xd0Ok-MkqoE"][cd_space desktop="30" tablet="30" portrait="30" mobile="30" mobile_portrait="30"][cd_section_title heading_tag="h3" title_align="text-center" style="style_3" section_title="Want To Know More About? Play Our Promotional Video Now!" title_font_size_lg="" title_font_size_md="" title_font_size_sm="36" title_font_size_xs="32" title_line_height_lg="" title_line_height_md="" title_line_height_sm="46" title_line_height_xs="42"]</p>
<h2 class="main-title">We provides best solution EV vehicles</h2>
<p>[/cd_section_title][/vc_column][vc_column offset="vc_col-lg-2 vc_col-md-1"][/vc_column][/vc_row][vc_row css=".vc_custom_1697449331307{margin-top: -125px !important;margin-right: 0px !important;margin-left: 0px !important;padding-top: 50px !important;padding-right: 70px !important;padding-bottom: 50px !important;padding-left: 70px !important;background-color: #db2d2e !important;border-radius: 10px !important;}"][vc_column][vc_row_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-6 vc_col-xs-12" css=".vc_custom_1697449231163{padding-top: 20px !important;padding-bottom: 20px !important;}"][cd_counter counter_speed="10000" counter_suffix="k" label_color="#ffffff" counter_color="#ffffff" element_id="c5a59824-5d59-8" style="style-5" label="Vehicles in Stock" counter="3968"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-6 vc_col-xs-12" css=".vc_custom_1697449239498{padding-top: 20px !important;padding-bottom: 20px !important;}"][cd_counter counter_speed="10000" counter_suffix="+" label_color="#ffffff" counter_color="#ffffff" element_id="c5a59824-5d59-8" style="style-5" label="Years Experience" counter="25"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-6 vc_col-xs-12" css=".vc_custom_1697449247114{padding-top: 20px !important;padding-bottom: 20px !important;}"][cd_counter counter_speed="10000" counter_suffix="+" label_color="#ffffff" counter_color="#ffffff" element_id="c5a59824-5d59-8" style="style-5" label="Satisfied Clients" counter="3990"][/vc_column_inner][vc_column_inner width="1/2" offset="vc_col-lg-3 vc_col-md-6 vc_col-xs-12" css=".vc_custom_1697449254938{padding-top: 20px !important;padding-bottom: 20px !important;}"][cd_counter counter_speed="10000" counter_suffix="+" label_color="#ffffff" counter_color="#ffffff" element_id="c5a59824-5d59-8" style="style-5" label="Dealer Review" counter="150"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]</p>
CONTENT',
);
